// Generated by gencpp from file bmirobot_move/GraspServoResponse.msg
// DO NOT EDIT!


#ifndef BMIROBOT_MOVE_MESSAGE_GRASPSERVORESPONSE_H
#define BMIROBOT_MOVE_MESSAGE_GRASPSERVORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bmirobot_move
{
template <class ContainerAllocator>
struct GraspServoResponse_
{
  typedef GraspServoResponse_<ContainerAllocator> Type;

  GraspServoResponse_()
    : status(0)  {
    }
  GraspServoResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GraspServoResponse_

typedef ::bmirobot_move::GraspServoResponse_<std::allocator<void> > GraspServoResponse;

typedef boost::shared_ptr< ::bmirobot_move::GraspServoResponse > GraspServoResponsePtr;
typedef boost::shared_ptr< ::bmirobot_move::GraspServoResponse const> GraspServoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bmirobot_move::GraspServoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bmirobot_move::GraspServoResponse_<ContainerAllocator1> & lhs, const ::bmirobot_move::GraspServoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bmirobot_move::GraspServoResponse_<ContainerAllocator1> & lhs, const ::bmirobot_move::GraspServoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bmirobot_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86791dcf1de997ec7de5a0de7e4dcfcc";
  }

  static const char* value(const ::bmirobot_move::GraspServoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86791dcf1de997ecULL;
  static const uint64_t static_value2 = 0x7de5a0de7e4dcfccULL;
};

template<class ContainerAllocator>
struct DataType< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bmirobot_move/GraspServoResponse";
  }

  static const char* value(const ::bmirobot_move::GraspServoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"\n"
;
  }

  static const char* value(const ::bmirobot_move::GraspServoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspServoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bmirobot_move::GraspServoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bmirobot_move::GraspServoResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BMIROBOT_MOVE_MESSAGE_GRASPSERVORESPONSE_H
