; Auto-generated. Do not edit!


(cl:in-package bmirobot_tools-msg)


;//! \htmlinclude PointsPR.msg.html

(cl:defclass <PointsPR> (roslisp-msg-protocol:ros-message)
  ((Px
    :reader Px
    :initarg :Px
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0))
   (Py
    :reader Py
    :initarg :Py
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0))
   (Pz
    :reader Pz
    :initarg :Pz
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0))
   (Rx
    :reader Rx
    :initarg :Rx
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0))
   (Ry
    :reader Ry
    :initarg :Ry
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0))
   (Rz
    :reader Rz
    :initarg :Rz
    :type (cl:vector cl:float)
   :initform (cl:make-array 4 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass PointsPR (<PointsPR>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PointsPR>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PointsPR)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bmirobot_tools-msg:<PointsPR> is deprecated: use bmirobot_tools-msg:PointsPR instead.")))

(cl:ensure-generic-function 'Px-val :lambda-list '(m))
(cl:defmethod Px-val ((m <PointsPR>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bmirobot_tools-msg:Px-val is deprecated.  Use bmirobot_tools-msg:Px instead.")
  (Px m))

(cl:ensure-generic-function 'Py-val :lambda-list '(m))
(cl:defmethod Py-val ((m <PointsPR>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bmirobot_tools-msg:Py-val is deprecated.  Use bmirobot_tools-msg:Py instead.")
  (Py m))

(cl:ensure-generic-function 'Pz-val :lambda-list '(m))
(cl:defmethod Pz-val ((m <PointsPR>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bmirobot_tools-msg:Pz-val is deprecated.  Use bmirobot_tools-msg:Pz instead.")
  (Pz m))

(cl:ensure-generic-function 'Rx-val :lambda-list '(m))
(cl:defmethod Rx-val ((m <PointsPR>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bmirobot_tools-msg:Rx-val is deprecated.  Use bmirobot_tools-msg:Rx instead.")
  (Rx m))

(cl:ensure-generic-function 'Ry-val :lambda-list '(m))
(cl:defmethod Ry-val ((m <PointsPR>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bmirobot_tools-msg:Ry-val is deprecated.  Use bmirobot_tools-msg:Ry instead.")
  (Ry m))

(cl:ensure-generic-function 'Rz-val :lambda-list '(m))
(cl:defmethod Rz-val ((m <PointsPR>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader bmirobot_tools-msg:Rz-val is deprecated.  Use bmirobot_tools-msg:Rz instead.")
  (Rz m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PointsPR>) ostream)
  "Serializes a message object of type '<PointsPR>"
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Px))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Py))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Pz))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Rx))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Ry))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'Rz))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PointsPR>) istream)
  "Deserializes a message object of type '<PointsPR>"
  (cl:setf (cl:slot-value msg 'Px) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'Px)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'Py) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'Py)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'Pz) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'Pz)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'Rx) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'Rx)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'Ry) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'Ry)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  (cl:setf (cl:slot-value msg 'Rz) (cl:make-array 4))
  (cl:let ((vals (cl:slot-value msg 'Rz)))
    (cl:dotimes (i 4)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PointsPR>)))
  "Returns string type for a message object of type '<PointsPR>"
  "bmirobot_tools/PointsPR")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PointsPR)))
  "Returns string type for a message object of type 'PointsPR"
  "bmirobot_tools/PointsPR")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PointsPR>)))
  "Returns md5sum for a message object of type '<PointsPR>"
  "5f5a7d3cfad1346be5c8446784c69a6c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PointsPR)))
  "Returns md5sum for a message object of type 'PointsPR"
  "5f5a7d3cfad1346be5c8446784c69a6c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PointsPR>)))
  "Returns full string definition for message of type '<PointsPR>"
  (cl:format cl:nil "float64[4] Px~%float64[4] Py~%float64[4] Pz~%float64[4] Rx~%float64[4] Ry~%float64[4] Rz~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PointsPR)))
  "Returns full string definition for message of type 'PointsPR"
  (cl:format cl:nil "float64[4] Px~%float64[4] Py~%float64[4] Pz~%float64[4] Rx~%float64[4] Ry~%float64[4] Rz~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PointsPR>))
  (cl:+ 0
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'Px) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'Py) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'Pz) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'Rx) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'Ry) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     0 (cl:reduce #'cl:+ (cl:slot-value msg 'Rz) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PointsPR>))
  "Converts a ROS message object to a list"
  (cl:list 'PointsPR
    (cl:cons ':Px (Px msg))
    (cl:cons ':Py (Py msg))
    (cl:cons ':Pz (Pz msg))
    (cl:cons ':Rx (Rx msg))
    (cl:cons ':Ry (Ry msg))
    (cl:cons ':Rz (Rz msg))
))
