// Generated by gencpp from file control_try/simulateResponse.msg
// DO NOT EDIT!


#ifndef CONTROL_TRY_MESSAGE_SIMULATERESPONSE_H
#define CONTROL_TRY_MESSAGE_SIMULATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_try
{
template <class ContainerAllocator>
struct simulateResponse_
{
  typedef simulateResponse_<ContainerAllocator> Type;

  simulateResponse_()
    : joint()  {
    }
  simulateResponse_(const ContainerAllocator& _alloc)
    : joint(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_type;
  _joint_type joint;





  typedef boost::shared_ptr< ::control_try::simulateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_try::simulateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simulateResponse_

typedef ::control_try::simulateResponse_<std::allocator<void> > simulateResponse;

typedef boost::shared_ptr< ::control_try::simulateResponse > simulateResponsePtr;
typedef boost::shared_ptr< ::control_try::simulateResponse const> simulateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_try::simulateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_try::simulateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_try::simulateResponse_<ContainerAllocator1> & lhs, const ::control_try::simulateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joint == rhs.joint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_try::simulateResponse_<ContainerAllocator1> & lhs, const ::control_try::simulateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_try

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_try::simulateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_try::simulateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_try::simulateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_try::simulateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_try::simulateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_try::simulateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_try::simulateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d98f45f5f7d408b6a0d45a64e4813c5";
  }

  static const char* value(const ::control_try::simulateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d98f45f5f7d408bULL;
  static const uint64_t static_value2 = 0x6a0d45a64e4813c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_try::simulateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_try/simulateResponse";
  }

  static const char* value(const ::control_try::simulateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_try::simulateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint\n"
"\n"
;
  }

  static const char* value(const ::control_try::simulateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_try::simulateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_try::simulateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_try::simulateResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint[]" << std::endl;
    for (size_t i = 0; i < v.joint.size(); ++i)
    {
      s << indent << "  joint[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_TRY_MESSAGE_SIMULATERESPONSE_H
