(cl:in-package bmirobot_msg-msg)
(cl:export '(MT_MODE-VAL
          MT_MODE
          MT_GPST-VAL
          MT_GPST
          MT_CPST-VAL
          MT_CPST
          MT_LPST-VAL
          MT_LPST
          MT_GSPD-VAL
          MT_GSPD
          MT_CSPD-VAL
          MT_CSPD
          MT_LSPD-VAL
          MT_LSPD
          MT_GTQ-VAL
          MT_GTQ
          MT_PWMDUTY-VAL
          MT_PWMDUTY
          MT_GTIME-VAL
          MT_GTIME
          MT_CTIME-VAL
          MT_CTIME
          MT_RTIME-VAL
          MT_RTIME
          MT_SYSCLK-VAL
          MT_SYSCLK
          MT_SMPTIME-VAL
          MT_SMPTIME
          MT_CPUTMP-VAL
          MT_CPUTMP
          MT_MTTMP-VAL
          MT_MTTMP
          MT_INVLT-VAL
          MT_INVLT
          MT_INCRT-VAL
          MT_INCRT
          MT_PWMFRQ-VAL
          MT_PWMFRQ
          MT_ECD-VAL
          MT_ECD
          MT_ECDCNT-VAL
          MT_ECDCNT
))