set(_CATKIN_CURRENT_PACKAGE "bmirobot_moveit_v52")
set(bmirobot_moveit_v52_VERSION "0.3.0")
set(bmirobot_moveit_v52_MAINTAINER "chenpeng <cpdream@foxmail.com>")
set(bmirobot_moveit_v52_PACKAGE_FORMAT "1")
set(bmirobot_moveit_v52_BUILD_DEPENDS )
set(bmirobot_moveit_v52_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "bmirobot_description")
set(bmirobot_moveit_v52_BUILDTOOL_DEPENDS "catkin")
set(bmirobot_moveit_v52_BUILDTOOL_EXPORT_DEPENDS )
set(bmirobot_moveit_v52_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "bmirobot_description")
set(bmirobot_moveit_v52_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners" "moveit_ros_visualization" "moveit_setup_assistant" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz" "tf2_ros" "xacro" "bmirobot_description")
set(bmirobot_moveit_v52_TEST_DEPENDS )
set(bmirobot_moveit_v52_DOC_DEPENDS )
set(bmirobot_moveit_v52_URL_WEBSITE "http://moveit.ros.org/")
set(bmirobot_moveit_v52_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(bmirobot_moveit_v52_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(bmirobot_moveit_v52_DEPRECATED "")