// Generated by gencpp from file control_try/simulateRequest.msg
// DO NOT EDIT!


#ifndef CONTROL_TRY_MESSAGE_SIMULATEREQUEST_H
#define CONTROL_TRY_MESSAGE_SIMULATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_try
{
template <class ContainerAllocator>
struct simulateRequest_
{
  typedef simulateRequest_<ContainerAllocator> Type;

  simulateRequest_()
    : a(0)  {
    }
  simulateRequest_(const ContainerAllocator& _alloc)
    : a(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::control_try::simulateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_try::simulateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simulateRequest_

typedef ::control_try::simulateRequest_<std::allocator<void> > simulateRequest;

typedef boost::shared_ptr< ::control_try::simulateRequest > simulateRequestPtr;
typedef boost::shared_ptr< ::control_try::simulateRequest const> simulateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_try::simulateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_try::simulateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_try::simulateRequest_<ContainerAllocator1> & lhs, const ::control_try::simulateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_try::simulateRequest_<ContainerAllocator1> & lhs, const ::control_try::simulateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_try

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_try::simulateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_try::simulateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_try::simulateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_try::simulateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_try::simulateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_try::simulateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_try::simulateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c9fb1a886e81e3162a5c87bf55c072b";
  }

  static const char* value(const ::control_try::simulateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c9fb1a886e81e31ULL;
  static const uint64_t static_value2 = 0x62a5c87bf55c072bULL;
};

template<class ContainerAllocator>
struct DataType< ::control_try::simulateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_try/simulateRequest";
  }

  static const char* value(const ::control_try::simulateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_try::simulateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
"\n"
;
  }

  static const char* value(const ::control_try::simulateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_try::simulateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_try::simulateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_try::simulateRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_TRY_MESSAGE_SIMULATEREQUEST_H
