set(_CATKIN_CURRENT_PACKAGE "bmirobotv5")
set(bmirobotv5_VERSION "0.2.0")
set(bmirobotv5_MAINTAINER "MoveIt Setup Assistant <assistant@moveit.ros.org>")
set(bmirobotv5_PACKAGE_FORMAT "1")
set(bmirobotv5_BUILD_DEPENDS "bmirobot_description")
set(bmirobotv5_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "bmirobot_description")
set(bmirobotv5_BUILDTOOL_DEPENDS "catkin")
set(bmirobotv5_BUILDTOOL_EXPORT_DEPENDS )
set(bmirobotv5_EXEC_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "bmirobot_description")
set(bmirobotv5_RUN_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro" "bmirobot_description")
set(bmirobotv5_TEST_DEPENDS )
set(bmirobotv5_DOC_DEPENDS )
set(bmirobotv5_URL_WEBSITE "http://moveit.ros.org/")
set(bmirobotv5_URL_BUGTRACKER "https://github.com/ros-planning/moveit_setup_assistant/issues")
set(bmirobotv5_URL_REPOSITORY "https://github.com/ros-planning/moveit_setup_assistant")
set(bmirobotv5_DEPRECATED "")