bmirobot:
    gazebo_ros_control:
        pid_gains:
            left_joint1:
                p: 0.0
                i: 0.0
                d: 0.0
            left_joint2:
                p: 0.0
                i: 0.0
                d: 0.0
            left_joint3:
                p: 0.0
                i: 0.0
                d: 0.0
            left_joint4:
                p: 0.0
                i: 0.0
                d: 0.0
            left_joint5:
                p: 0.0
                i: 0.0
                d: 0.0
            left_joint6:
                p: 0.0
                i: 0.0
                d: 0.0
            left_joint7:
                p: 0.0
                i: 0.0
                d: 0.0
            left_joint8:
                p: 0.0
                i: 0.0
                d: 0.0
            left_hand_joint1:
                p: 0.0
                i: 0.0
                d: 0.0
            left_hand_joint2:
                p: 0.0
                i: 0.0
                d: 0.0
            right_joint1:
                p: 0.0
                i: 0.0
                d: 0.0
            right_joint2:
                p: 0.0
                i: 0.0
                d: 0.0
            right_joint3:
                p: 0.0
                i: 0.0
                d: 0.0
            right_joint4:
                p: 0.0
                i: 0.0
                d: 0.0
            right_joint5:
                p: 0.0
                i: 0.0
                d: 0.0
            right_joint6:
                p: 0.0
                i: 0.0
                d: 0.0
            right_joint7:
                p: 0.0
                i: 0.0
                d: 0.0
            right_joint8:
                p: 0.0
                i: 0.0
                d: 0.0
            right_hand_joint1:
                p: 0.0
                i: 0.0
                d: 0.0
            right_hand_joint2:
                p: 0.0
                i: 0.0
                d: 0.0


