# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bmirobot_msg/Robot_ctr.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Robot_ctr(genpy.Message):
  _md5sum = "0fc2a2db85d9265b43f59ed7bec2ae3c"
  _type = "bmirobot_msg/Robot_ctr"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32[9] mtID
int32[9] mtmode
int32[9] mtpst
int32[9] mtspd
int32[9] mttq
"""
  __slots__ = ['mtID','mtmode','mtpst','mtspd','mttq']
  _slot_types = ['int32[9]','int32[9]','int32[9]','int32[9]','int32[9]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mtID,mtmode,mtpst,mtspd,mttq

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Robot_ctr, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mtID is None:
        self.mtID = [0] * 9
      if self.mtmode is None:
        self.mtmode = [0] * 9
      if self.mtpst is None:
        self.mtpst = [0] * 9
      if self.mtspd is None:
        self.mtspd = [0] * 9
      if self.mttq is None:
        self.mttq = [0] * 9
    else:
      self.mtID = [0] * 9
      self.mtmode = [0] * 9
      self.mtpst = [0] * 9
      self.mtspd = [0] * 9
      self.mttq = [0] * 9

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_9i().pack(*self.mtID))
      buff.write(_get_struct_9i().pack(*self.mtmode))
      buff.write(_get_struct_9i().pack(*self.mtpst))
      buff.write(_get_struct_9i().pack(*self.mtspd))
      buff.write(_get_struct_9i().pack(*self.mttq))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 36
      self.mtID = _get_struct_9i().unpack(str[start:end])
      start = end
      end += 36
      self.mtmode = _get_struct_9i().unpack(str[start:end])
      start = end
      end += 36
      self.mtpst = _get_struct_9i().unpack(str[start:end])
      start = end
      end += 36
      self.mtspd = _get_struct_9i().unpack(str[start:end])
      start = end
      end += 36
      self.mttq = _get_struct_9i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.mtID.tostring())
      buff.write(self.mtmode.tostring())
      buff.write(self.mtpst.tostring())
      buff.write(self.mtspd.tostring())
      buff.write(self.mttq.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 36
      self.mtID = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=9)
      start = end
      end += 36
      self.mtmode = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=9)
      start = end
      end += 36
      self.mtpst = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=9)
      start = end
      end += 36
      self.mtspd = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=9)
      start = end
      end += 36
      self.mttq = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=9)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9i = None
def _get_struct_9i():
    global _struct_9i
    if _struct_9i is None:
        _struct_9i = struct.Struct("<9i")
    return _struct_9i
