set(_CATKIN_CURRENT_PACKAGE "test_robot")
set(test_robot_VERSION "0.2.0")
set(test_robot_MAINTAINER "MoveIt Setup Assistant <assistant@moveit.ros.org>")
set(test_robot_PACKAGE_FORMAT "1")
set(test_robot_BUILD_DEPENDS )
set(test_robot_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro")
set(test_robot_BUILDTOOL_DEPENDS "catkin")
set(test_robot_BUILDTOOL_EXPORT_DEPENDS )
set(test_robot_EXEC_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro")
set(test_robot_RUN_DEPENDS "moveit_ros_move_group" "moveit_planners_ompl" "moveit_ros_visualization" "joint_state_publisher" "robot_state_publisher" "xacro")
set(test_robot_TEST_DEPENDS )
set(test_robot_DOC_DEPENDS )
set(test_robot_URL_WEBSITE "http://moveit.ros.org/")
set(test_robot_URL_BUGTRACKER "https://github.com/ros-planning/moveit_setup_assistant/issues")
set(test_robot_URL_REPOSITORY "https://github.com/ros-planning/moveit_setup_assistant")
set(test_robot_DEPRECATED "")