# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bmirobot_msg/Robot_mpu.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Robot_mpu(genpy.Message):
  _md5sum = "742fca3c0a78013d1f45f4495e1ad202"
  _type = "bmirobot_msg/Robot_mpu"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16[8] mpu_Ax
int16[8] mpu_Ay
int16[8] mpu_Az
int16[8] mpu_Rx
int16[8] mpu_Ry
int16[8] mpu_Rz
"""
  __slots__ = ['mpu_Ax','mpu_Ay','mpu_Az','mpu_Rx','mpu_Ry','mpu_Rz']
  _slot_types = ['int16[8]','int16[8]','int16[8]','int16[8]','int16[8]','int16[8]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mpu_Ax,mpu_Ay,mpu_Az,mpu_Rx,mpu_Ry,mpu_Rz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Robot_mpu, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mpu_Ax is None:
        self.mpu_Ax = [0] * 8
      if self.mpu_Ay is None:
        self.mpu_Ay = [0] * 8
      if self.mpu_Az is None:
        self.mpu_Az = [0] * 8
      if self.mpu_Rx is None:
        self.mpu_Rx = [0] * 8
      if self.mpu_Ry is None:
        self.mpu_Ry = [0] * 8
      if self.mpu_Rz is None:
        self.mpu_Rz = [0] * 8
    else:
      self.mpu_Ax = [0] * 8
      self.mpu_Ay = [0] * 8
      self.mpu_Az = [0] * 8
      self.mpu_Rx = [0] * 8
      self.mpu_Ry = [0] * 8
      self.mpu_Rz = [0] * 8

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_8h().pack(*self.mpu_Ax))
      buff.write(_get_struct_8h().pack(*self.mpu_Ay))
      buff.write(_get_struct_8h().pack(*self.mpu_Az))
      buff.write(_get_struct_8h().pack(*self.mpu_Rx))
      buff.write(_get_struct_8h().pack(*self.mpu_Ry))
      buff.write(_get_struct_8h().pack(*self.mpu_Rz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 16
      self.mpu_Ax = _get_struct_8h().unpack(str[start:end])
      start = end
      end += 16
      self.mpu_Ay = _get_struct_8h().unpack(str[start:end])
      start = end
      end += 16
      self.mpu_Az = _get_struct_8h().unpack(str[start:end])
      start = end
      end += 16
      self.mpu_Rx = _get_struct_8h().unpack(str[start:end])
      start = end
      end += 16
      self.mpu_Ry = _get_struct_8h().unpack(str[start:end])
      start = end
      end += 16
      self.mpu_Rz = _get_struct_8h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.mpu_Ax.tostring())
      buff.write(self.mpu_Ay.tostring())
      buff.write(self.mpu_Az.tostring())
      buff.write(self.mpu_Rx.tostring())
      buff.write(self.mpu_Ry.tostring())
      buff.write(self.mpu_Rz.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 16
      self.mpu_Ax = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=8)
      start = end
      end += 16
      self.mpu_Ay = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=8)
      start = end
      end += 16
      self.mpu_Az = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=8)
      start = end
      end += 16
      self.mpu_Rx = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=8)
      start = end
      end += 16
      self.mpu_Ry = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=8)
      start = end
      end += 16
      self.mpu_Rz = numpy.frombuffer(str[start:end], dtype=numpy.int16, count=8)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8h = None
def _get_struct_8h():
    global _struct_8h
    if _struct_8h is None:
        _struct_8h = struct.Struct("<8h")
    return _struct_8h
