# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bmirobot_msg/Robot_jointfd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Robot_jointfd(genpy.Message):
  _md5sum = "8b60b3db716c9968ae69daf16554d81f"
  _type = "bmirobot_msg/Robot_jointfd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32[9] Joint_fdpst
float32[9] Joint_fdspd
float32[9] Joint_fdctr

"""
  __slots__ = ['Joint_fdpst','Joint_fdspd','Joint_fdctr']
  _slot_types = ['float32[9]','float32[9]','float32[9]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Joint_fdpst,Joint_fdspd,Joint_fdctr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Robot_jointfd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Joint_fdpst is None:
        self.Joint_fdpst = [0.] * 9
      if self.Joint_fdspd is None:
        self.Joint_fdspd = [0.] * 9
      if self.Joint_fdctr is None:
        self.Joint_fdctr = [0.] * 9
    else:
      self.Joint_fdpst = [0.] * 9
      self.Joint_fdspd = [0.] * 9
      self.Joint_fdctr = [0.] * 9

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_9f().pack(*self.Joint_fdpst))
      buff.write(_get_struct_9f().pack(*self.Joint_fdspd))
      buff.write(_get_struct_9f().pack(*self.Joint_fdctr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 36
      self.Joint_fdpst = _get_struct_9f().unpack(str[start:end])
      start = end
      end += 36
      self.Joint_fdspd = _get_struct_9f().unpack(str[start:end])
      start = end
      end += 36
      self.Joint_fdctr = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.Joint_fdpst.tostring())
      buff.write(self.Joint_fdspd.tostring())
      buff.write(self.Joint_fdctr.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 36
      self.Joint_fdpst = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=9)
      start = end
      end += 36
      self.Joint_fdspd = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=9)
      start = end
      end += 36
      self.Joint_fdctr = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=9)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9f = None
def _get_struct_9f():
    global _struct_9f
    if _struct_9f is None:
        _struct_9f = struct.Struct("<9f")
    return _struct_9f
