# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bmirobot_msg/Robot_fdctr.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Robot_fdctr(genpy.Message):
  _md5sum = "3195cf007256e8ddfd66fc62f56f5233"
  _type = "bmirobot_msg/Robot_fdctr"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32[9] mt_mode
int32[9] mt_Cpst
int32[9] mt_Cspd
int32[9] mt_incrt
int32[9] mt_PWMduty
"""
  __slots__ = ['mt_mode','mt_Cpst','mt_Cspd','mt_incrt','mt_PWMduty']
  _slot_types = ['int32[9]','int32[9]','int32[9]','int32[9]','int32[9]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mt_mode,mt_Cpst,mt_Cspd,mt_incrt,mt_PWMduty

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Robot_fdctr, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mt_mode is None:
        self.mt_mode = [0] * 9
      if self.mt_Cpst is None:
        self.mt_Cpst = [0] * 9
      if self.mt_Cspd is None:
        self.mt_Cspd = [0] * 9
      if self.mt_incrt is None:
        self.mt_incrt = [0] * 9
      if self.mt_PWMduty is None:
        self.mt_PWMduty = [0] * 9
    else:
      self.mt_mode = [0] * 9
      self.mt_Cpst = [0] * 9
      self.mt_Cspd = [0] * 9
      self.mt_incrt = [0] * 9
      self.mt_PWMduty = [0] * 9

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_9i().pack(*self.mt_mode))
      buff.write(_get_struct_9i().pack(*self.mt_Cpst))
      buff.write(_get_struct_9i().pack(*self.mt_Cspd))
      buff.write(_get_struct_9i().pack(*self.mt_incrt))
      buff.write(_get_struct_9i().pack(*self.mt_PWMduty))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 36
      self.mt_mode = _get_struct_9i().unpack(str[start:end])
      start = end
      end += 36
      self.mt_Cpst = _get_struct_9i().unpack(str[start:end])
      start = end
      end += 36
      self.mt_Cspd = _get_struct_9i().unpack(str[start:end])
      start = end
      end += 36
      self.mt_incrt = _get_struct_9i().unpack(str[start:end])
      start = end
      end += 36
      self.mt_PWMduty = _get_struct_9i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.mt_mode.tostring())
      buff.write(self.mt_Cpst.tostring())
      buff.write(self.mt_Cspd.tostring())
      buff.write(self.mt_incrt.tostring())
      buff.write(self.mt_PWMduty.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 36
      self.mt_mode = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=9)
      start = end
      end += 36
      self.mt_Cpst = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=9)
      start = end
      end += 36
      self.mt_Cspd = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=9)
      start = end
      end += 36
      self.mt_incrt = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=9)
      start = end
      end += 36
      self.mt_PWMduty = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=9)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9i = None
def _get_struct_9i():
    global _struct_9i
    if _struct_9i is None:
        _struct_9i = struct.Struct("<9i")
    return _struct_9i
