set(_CATKIN_CURRENT_PACKAGE "bmirobot_description")
set(bmirobot_description_VERSION "0.0.0")
set(bmirobot_description_MAINTAINER "bmi <bmi@todo.todo>")
set(bmirobot_description_PACKAGE_FORMAT "1")
set(bmirobot_description_BUILD_DEPENDS )
set(bmirobot_description_BUILD_EXPORT_DEPENDS )
set(bmirobot_description_BUILDTOOL_DEPENDS "catkin")
set(bmirobot_description_BUILDTOOL_EXPORT_DEPENDS )
set(bmirobot_description_EXEC_DEPENDS )
set(bmirobot_description_RUN_DEPENDS )
set(bmirobot_description_TEST_DEPENDS )
set(bmirobot_description_DOC_DEPENDS )
set(bmirobot_description_URL_WEBSITE "")
set(bmirobot_description_URL_BUGTRACKER "")
set(bmirobot_description_URL_REPOSITORY "")
set(bmirobot_description_DEPRECATED "")