set(_CATKIN_CURRENT_PACKAGE "robotarm_moveit")
set(robotarm_moveit_VERSION "0.3.0")
set(robotarm_moveit_MAINTAINER "ddd <ddd@sina.com>")
set(robotarm_moveit_PACKAGE_FORMAT "1")
set(robotarm_moveit_BUILD_DEPENDS "robotarm_description")
set(robotarm_moveit_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "robotarm_description")
set(robotarm_moveit_BUILDTOOL_DEPENDS "catkin")
set(robotarm_moveit_BUILDTOOL_EXPORT_DEPENDS )
set(robotarm_moveit_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "robotarm_description")
set(robotarm_moveit_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "xacro" "robotarm_description")
set(robotarm_moveit_TEST_DEPENDS )
set(robotarm_moveit_DOC_DEPENDS )
set(robotarm_moveit_URL_WEBSITE "http://moveit.ros.org/")
set(robotarm_moveit_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(robotarm_moveit_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(robotarm_moveit_DEPRECATED "")