robotarm:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - right_joint1
        - right_joint2
        - right_joint3
        - right_joint4
        - right_joint5
        - right_joint6
        - right_joint7
        - left_joint1
        - left_joint2
        - left_joint3
        - left_joint4
        - left_joint5
        - left_joint6
        - left_joint7


    gains:
      right_joint1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      right_joint2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      right_joint3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      right_joint4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      right_joint5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      right_joint6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      right_joint7:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_joint1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_joint2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_joint3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_joint4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_joint5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_joint6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      left_joint7:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
