robotarm:
    gazebo_ros_control:
        pid_gains:
            left_joint1:
                p: 1000.0
                i: 0.005
                d: 100.0
            left_joint2:
                p: 1000.0
                i: 0.005
                d: 100.0
            left_joint3:
                p: 1000.0
                i: 0.005
                d: 100.0
            left_joint4:
                p: 1000.0
                i: 0.005
                d: 100.0
            left_joint5:
                p: 1000.0
                i: 0.005
                d: 100.0
            left_joint6:
                p: 1000.0
                i: 0.005
                d: 100.0
            left_joint7:
                p: 1000.0
                i: 0.005
                d: 100.0
            left_joint8:
                p: 1000.0
                i: 0.005
                d: 100.0
            left_hand_joint1:
                p: 1000.0
                i: 0.005
                d: 100.0
            left_hand_joint2:
                p: 1000.0
                i: 0.005
                d: 100.0
            right_joint1:
                p: 1000.0
                i: 0.005
                d: 100.0
            right_joint2:
                p: 1000.0
                i: 0.005
                d: 100.0
            right_joint3:
                p: 1000.0
                i: 0.005
                d: 100.0
            right_joint4:
                p: 1000.0
                i: 0.005
                d: 100.0
            right_joint5:
                p: 1000.0
                i: 0.005
                d: 100.0
            right_joint6:
                p: 1000.0
                i: 0.005
                d: 100.0
            right_joint7:
                p: 1000.0
                i: 0.005
                d: 100.0
            right_joint8:
                p: 1000.0
                i: 0.005
                d: 100.0
            right_hand_joint1:
                p: 1000.0
                i: 0.005
                d: 100.0
            right_hand_joint2:
                p: 1000.0
                i: 0.005
                d: 100.0
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    joint_trajectory_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - right_joint1
        - right_joint2
        - right_joint3
        - right_joint4
        - right_joint5
        - right_joint6
        - right_joint7
        - right_joint8
        - left_joint1
        - left_joint2
        - left_joint3
        - left_joint4
        - left_joint5
        - left_joint6
        - left_joint7
        - left_joint8
      constraints:
        stop_trajectory_duration: 0.5
      initial_positions:
        right_joint1: 0.0 
        right_joint2: 0.0 
        right_joint3: 0.0 
        right_joint4: 0.0
        right_joint5: 0.0 
        right_joint6: 0.0
        right_joint7: 0.0 
        right_joint8: 0.0  
        left_joint1: 0.0 
        left_joint2: 0.0 
        left_joint3: 0.0 
        left_joint4: 0.0
        left_joint5: 0.0 
        left_joint6: 0.0
        left_joint7: 0.0 
        left_joint8: 0.0
