set(_CATKIN_CURRENT_PACKAGE "bmirobot_gazebo")
set(bmirobot_gazebo_VERSION "0.0.0")
set(bmirobot_gazebo_MAINTAINER "bmi <bmi@todo.todo>")
set(bmirobot_gazebo_PACKAGE_FORMAT "1")
set(bmirobot_gazebo_BUILD_DEPENDS )
set(bmirobot_gazebo_BUILD_EXPORT_DEPENDS )
set(bmirobot_gazebo_BUILDTOOL_DEPENDS "catkin")
set(bmirobot_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(bmirobot_gazebo_EXEC_DEPENDS )
set(bmirobot_gazebo_RUN_DEPENDS )
set(bmirobot_gazebo_TEST_DEPENDS )
set(bmirobot_gazebo_DOC_DEPENDS )
set(bmirobot_gazebo_URL_WEBSITE "")
set(bmirobot_gazebo_URL_BUGTRACKER "")
set(bmirobot_gazebo_URL_REPOSITORY "")
set(bmirobot_gazebo_DEPRECATED "")