set(_CATKIN_CURRENT_PACKAGE "bmirobot_move")
set(bmirobot_move_VERSION "1.3.1")
set(bmirobot_move_MAINTAINER "Dave Coleman <davetcoleman@gmail.com>")
set(bmirobot_move_PACKAGE_FORMAT "1")
set(bmirobot_move_BUILD_DEPENDS "roscpp" "eigen_conversions" "std_msgs" "trajectory_msgs" "tf" "tf_conversions" "moveit_ros_planning" "moveit_ros_planning_interface" "moveit_core" "moveit_visual_tools" "message_generation" "actionlib" "moveit_msgs" "geometry_msgs" "actionlib_msgs" "cmake_modules" "moveit_simple_grasps" "object_recognition_msgs" "libpcl-all-dev" "bmirobot_msg")
set(bmirobot_move_BUILD_EXPORT_DEPENDS "std_msgs" "trajectory_msgs" "moveit_msgs" "geometry_msgs" "actionlib_msgs" "message_runtime" "moveit_visual_tools" "object_recognition_msgs" "bmirobot_msgs")
set(bmirobot_move_BUILDTOOL_DEPENDS "catkin")
set(bmirobot_move_BUILDTOOL_EXPORT_DEPENDS )
set(bmirobot_move_EXEC_DEPENDS "std_msgs" "trajectory_msgs" "moveit_msgs" "geometry_msgs" "actionlib_msgs" "message_runtime" "moveit_visual_tools" "object_recognition_msgs" "bmirobot_msgs")
set(bmirobot_move_RUN_DEPENDS "std_msgs" "trajectory_msgs" "moveit_msgs" "geometry_msgs" "actionlib_msgs" "message_runtime" "moveit_visual_tools" "object_recognition_msgs" "bmirobot_msgs")
set(bmirobot_move_TEST_DEPENDS )
set(bmirobot_move_DOC_DEPENDS )
set(bmirobot_move_URL_WEBSITE "https://github.com/davetcoleman/moveit_simple_grasps/")
set(bmirobot_move_URL_BUGTRACKER "https://github.com/davetcoleman/moveit_simple_grasps/issues")
set(bmirobot_move_URL_REPOSITORY "https://github.com/davetcoleman/moveit_simple_grasps")
set(bmirobot_move_DEPRECATED "")