// Generated by gencpp from file bmirobot_move/GraspServo.msg
// DO NOT EDIT!


#ifndef BMIROBOT_MOVE_MESSAGE_GRASPSERVO_H
#define BMIROBOT_MOVE_MESSAGE_GRASPSERVO_H

#include <ros/service_traits.h>


#include <bmirobot_move/GraspServoRequest.h>
#include <bmirobot_move/GraspServoResponse.h>


namespace bmirobot_move
{

struct GraspServo
{

typedef GraspServoRequest Request;
typedef GraspServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GraspServo
} // namespace bmirobot_move


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bmirobot_move::GraspServo > {
  static const char* value()
  {
    return "37b88a2b91372a258e4573b0ed517a08";
  }

  static const char* value(const ::bmirobot_move::GraspServo&) { return value(); }
};

template<>
struct DataType< ::bmirobot_move::GraspServo > {
  static const char* value()
  {
    return "bmirobot_move/GraspServo";
  }

  static const char* value(const ::bmirobot_move::GraspServo&) { return value(); }
};


// service_traits::MD5Sum< ::bmirobot_move::GraspServoRequest> should match
// service_traits::MD5Sum< ::bmirobot_move::GraspServo >
template<>
struct MD5Sum< ::bmirobot_move::GraspServoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bmirobot_move::GraspServo >::value();
  }
  static const char* value(const ::bmirobot_move::GraspServoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bmirobot_move::GraspServoRequest> should match
// service_traits::DataType< ::bmirobot_move::GraspServo >
template<>
struct DataType< ::bmirobot_move::GraspServoRequest>
{
  static const char* value()
  {
    return DataType< ::bmirobot_move::GraspServo >::value();
  }
  static const char* value(const ::bmirobot_move::GraspServoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bmirobot_move::GraspServoResponse> should match
// service_traits::MD5Sum< ::bmirobot_move::GraspServo >
template<>
struct MD5Sum< ::bmirobot_move::GraspServoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bmirobot_move::GraspServo >::value();
  }
  static const char* value(const ::bmirobot_move::GraspServoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bmirobot_move::GraspServoResponse> should match
// service_traits::DataType< ::bmirobot_move::GraspServo >
template<>
struct DataType< ::bmirobot_move::GraspServoResponse>
{
  static const char* value()
  {
    return DataType< ::bmirobot_move::GraspServo >::value();
  }
  static const char* value(const ::bmirobot_move::GraspServoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BMIROBOT_MOVE_MESSAGE_GRASPSERVO_H
