// Generated by gencpp from file bmirobot_move/GraspServoRequest.msg
// DO NOT EDIT!


#ifndef BMIROBOT_MOVE_MESSAGE_GRASPSERVOREQUEST_H
#define BMIROBOT_MOVE_MESSAGE_GRASPSERVOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace bmirobot_move
{
template <class ContainerAllocator>
struct GraspServoRequest_
{
  typedef GraspServoRequest_<ContainerAllocator> Type;

  GraspServoRequest_()
    : object_pose()  {
    }
  GraspServoRequest_(const ContainerAllocator& _alloc)
    : object_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _object_pose_type;
  _object_pose_type object_pose;





  typedef boost::shared_ptr< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GraspServoRequest_

typedef ::bmirobot_move::GraspServoRequest_<std::allocator<void> > GraspServoRequest;

typedef boost::shared_ptr< ::bmirobot_move::GraspServoRequest > GraspServoRequestPtr;
typedef boost::shared_ptr< ::bmirobot_move::GraspServoRequest const> GraspServoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bmirobot_move::GraspServoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bmirobot_move::GraspServoRequest_<ContainerAllocator1> & lhs, const ::bmirobot_move::GraspServoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.object_pose == rhs.object_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bmirobot_move::GraspServoRequest_<ContainerAllocator1> & lhs, const ::bmirobot_move::GraspServoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bmirobot_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f370b349a20e2e0029b6c926ba1b874";
  }

  static const char* value(const ::bmirobot_move::GraspServoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f370b349a20e2e0ULL;
  static const uint64_t static_value2 = 0x029b6c926ba1b874ULL;
};

template<class ContainerAllocator>
struct DataType< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bmirobot_move/GraspServoRequest";
  }

  static const char* value(const ::bmirobot_move::GraspServoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose object_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::bmirobot_move::GraspServoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspServoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bmirobot_move::GraspServoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bmirobot_move::GraspServoRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.object_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BMIROBOT_MOVE_MESSAGE_GRASPSERVOREQUEST_H
