set(_CATKIN_CURRENT_PACKAGE "bmirobot_msg")
set(bmirobot_msg_VERSION "0.0.0")
set(bmirobot_msg_MAINTAINER "bmi <bmi@todo.todo>")
set(bmirobot_msg_PACKAGE_FORMAT "1")
set(bmirobot_msg_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "message_generation")
set(bmirobot_msg_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(bmirobot_msg_BUILDTOOL_DEPENDS "catkin")
set(bmirobot_msg_BUILDTOOL_EXPORT_DEPENDS )
set(bmirobot_msg_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(bmirobot_msg_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(bmirobot_msg_TEST_DEPENDS )
set(bmirobot_msg_DOC_DEPENDS )
set(bmirobot_msg_URL_WEBSITE "")
set(bmirobot_msg_URL_BUGTRACKER "")
set(bmirobot_msg_URL_REPOSITORY "")
set(bmirobot_msg_DEPRECATED "")